-- Crear las tablas necesarias
CREATE TABLE EVENT (
    EVENT_ID NUMBER(38,0) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    NATION VARCHAR(25) NOT NULL CONSTRAINT NOT_EMPTY_NATION_EVENT CHECK(NATION <> ''),
    EVENT_NAME VARCHAR(40) NOT NULL CONSTRAINT NOT_EMPTY_EVENT_NAME_EVENT CHECK(EVENT_NAME <> ''),
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE ENTREGA(
    ID_PLAZO_ENTREGA INTEGER NOT NULL,
    DESCRIPCION VARCHAR(150) NOT NULL CONSTRAINT NOT_EMPTY_DESCRIPTION_ENTREGA CHECK(DESCRIPCION <> ''),
    PRIMARY KEY (ID_PLAZO_ENTREGA)
);

CREATE TABLE STORE(
    STORE_ID NUMBER(38,0) NOT NULL,
    NATION VARCHAR(25) NOT NULL CONSTRAINT NOT_EMPTY_NATION_STORE CHECK(NATION <> ''),
    NAME VARCHAR(20) NOT NULL CONSTRAINT NOT_EMPTY_NAME_STORE CHECK(NAME <> ''),
    ADDRESS VARCHAR(40) NOT NULL CONSTRAINT NOT_EMPTY_ADDRESS_STORE CHECK(ADDRESS <> ''),
    PRIMARY KEY (STORE_ID)
);

CREATE TABLE EXCHANGE_RATE (
    NATION VARCHAR(25) NOT NULL CONSTRAINT NOT_EMPTY_NATION_EXCHANGE_RATE CHECK(NATION <> ''),
    ORDER_DATE DATE NOT NULL,
    EXCHANGE_USD DECIMAL(38,2) NOT NULL,
    PRIMARY KEY (NATION, ORDER_DATE)
);

CREATE TABLE TIME_ZONE(
    NATION VARCHAR(25) NOT NULL CONSTRAINT NOT_EMPTY_NATION_TIME_ZONE CHECK(NATION <> ''),
    UTC TIMESTAMP_TZ NOT NULL,
    PRIMARY KEY (NATION)
);

CREATE TABLE DAILY_SALES(
    ORDER_DATE DATE NOT NULL,
    CUSTKEY NUMBER(38,0) NOT NULL,
    PARTKEY NUMBER(38,0) NOT NULL,
    SUPPKEY NUMBER(38,0) NOT NULL,
    ORDERKEY NUMBER(38,0) NOT NULL,
    ORDERTYPE ENUM('venta', 'devolucion') NOT NULL,
    STORE_ID NUMBER(38,0) NOT NULL,
    EVENT_ID NUMBER(38,0) NOT NULL,
    LOCAL_PRICE NUMBER(38,2) NOT NULL,
    CUSTOMER_PRICE NUMBER(38,2) NOT NULL,
    LOCAL_DATETIME TIMESTAMP_TZ NOT NULL,
    CUSTOMER_DATETIME TIMESTAMP_TZ NOT NULL,
    ID_PLAZO_ENTREGA NUMBER(38,0) NOT NULL,
    TAX NUMBER(12,2) NOT NULL,
    QUANTITY NUMBER(12,2) NOT NULL,
    LINENUMBER NUMBER(38,0) NOT NULL,
    LINESTATUS VARCHAR(1) NOT NULL CONSTRAINT NOT_EMPTY_LINESTATUS_DAILY_SALES CHECK(LINESTATUS <> ''),
    ORDER_STATUS VARCHAR(1) NOT NULL CONSTRAINT NOT_EMPTY_ORDER_STATUS_DAILY_SALES CHECK(ORDER_STATUS <> ''),
    ORDER_PRIORITY VARCHAR(15) NOT NULL CONSTRAINT NOT_EMPTY_ORDER_PRIORITY_DAILY_SALES CHECK(ORDER_PRIORITY <> ''),
    SHIP_DATE DATE NOT NULL,
    RETURN_FLAG VARCHAR(1) NOT NULL CONSTRAINT NOT_EMPTY_RETURN_FLAG_DAILY_SALES CHECK(RETURN_FLAG <> ''),
    COMMIT_DATE DATE NOT NULL,
    RECEIPT_DATE DATE NOT NULL,
    SHIP_INSTRUCT VARCHAR(25) NOT NULL CONSTRAINT NOT_EMPTY_SHIP_INSTRUCT_DAILY_SALES CHECK(ORDER_STATUS <> ''),
    SHIP_MODE VARCHAR(10) NOT NULL CONSTRAINT NOT_EMPTY_SHIP_MODE_DAILY_SALES CHECK(SHIP_MODE <> ''),
    CLERK NUMBER(38,0) NOT NULL,
    SHIP_PRIORITY NUMBER(38,0) NOT NULL,
    PRIMARY KEY (ORDER_DATE, ORDERKEY, PARTKEY, SUPPKEY, CUSTKEY)
);