WITH orders AS (
    SELECT * FROM {{ ref('stg_orders') }}
),
lineitems AS (
    SELECT * FROM {{ ref('stg_lineitem') }}
),
exchange_rates AS (
    SELECT * FROM {{ ref('stg_exchange_rate') }}
),
time_zones AS (
    SELECT * FROM {{ ref('stg_time_zone') }}
),
stores AS (
    SELECT * FROM {{ ref('stg_store') }}
),
events AS (
    SELECT * FROM {{ ref('stg_event') }}
),
entrega AS (
    SELECT * FROM {{ ref('stg_entrega') }}
),
daily_sales_raw AS (
    SELECT
        O.O_ORDERDATE AS ORDER_DATE,
        O.O_CUSTKEY AS CUSTKEY,
        L.L_PARTKEY AS PARTKEY,
        L.L_SUPPKEY AS SUPPKEY,
        O.O_ORDERKEY AS ORDERKEY,
        O.O_ORDERSTATUS AS ORDER_STATUS,
        S.STORE_ID,
        E.EVENT_ID,
        L.L_EXTENDEDPRICE AS LOCAL_PRICE,
        L.L_EXTENDEDPRICE * ER_STORE.EXCHANGE_USD AS CUSTOMER_PRICE,
        CONVERT_TIMEZONE('UTC', T_STORE.UTC, O.O_ORDERDATE) AS LOCAL_DATETIME,
        CONVERT_TIMEZONE('UTC', T_CUSTOMER.UTC, O.O_ORDERDATE) AS CUSTOMER_DATETIME,
        CASE
            WHEN DATEDIFF(day, L.L_RECEIPTDATE, L.L_COMMITDATE) > 30 THEN 0
            WHEN DATEDIFF(day, L.L_RECEIPTDATE, L.L_COMMITDATE) <= 0 THEN 1
            WHEN DATEDIFF(day, L.L_RECEIPTDATE, L.L_COMMITDATE) BETWEEN 1 AND 10 THEN 2
            WHEN DATEDIFF(day, L.L_RECEIPTDATE, L.L_COMMITDATE) BETWEEN 11 AND 30 THEN 3
        END AS ID_PLAZO_ENTREGA,
        L.L_TAX AS TAX,
        L.L_QUANTITY AS QUANTITY,
        L.L_LINENUMBER AS LINENUMBER,
        L.L_LINESTATUS AS LINESTATUS,
        O.O_ORDERPRIORITY AS ORDER_PRIORITY,
        L.L_SHIPDATE AS SHIP_DATE,
        L.L_RETURNFLAG AS RETURN_FLAG,
        L.L_COMMITDATE AS COMMIT_DATE,
        L.L_RECEIPTDATE AS RECEIPT_DATE,
        L.L_SHIPINSTRUCT AS SHIP_INSTRUCT,
        L.L_SHIPMODE AS SHIP_MODE,
        CAST(REGEXP_SUBSTR(O.O_CLERK, '[0-9]+') AS NUMBER) AS CLERK
    FROM orders O
    JOIN lineitems L ON O.O_ORDERKEY = L.L_ORDERKEY
    JOIN stores S ON S.STORE_ID = L.L_SUPPKEY
    JOIN events E ON O.O_ORDERDATE BETWEEN E.START_DATE AND E.END_DATE
    JOIN exchange_rates ER_STORE ON S.NATION = ER_STORE.NATION AND O.O_ORDERDATE = ER_STORE.ORDER_DATE
    JOIN exchange_rates ER_CUSTOMER ON O.O_CUSTKEY = ER_CUSTOMER.NATION AND O.O_ORDERDATE = ER_CUSTOMER.ORDER_DATE
    JOIN time_zones T_STORE ON S.NATION = T_STORE.NATION
    JOIN time_zones T_CUSTOMER ON O.O_CUSTKEY = T_CUSTOMER.NATION
    WHERE O.O_ORDERDATE >= CURRENT_DATE - INTERVAL '30 DAY'
    AND L.L_SHIPDATE IS NOT NULL
)


SELECT * FROM daily_sales_raw
