-- Código para insertar ventas diarias
CREATE PROCEDURE populate_daily_sales()
RETURNS STRING
LANGUAGE SQL
AS
$$
    INSERT INTO DAILY_SALES (
        ORDER_DATE, CUSTKEY, PARTKEY, SUPPKEY, ORDERKEY, ORDERTYPE,
        STORE_ID, EVENT_ID, LOCAL_PRICE, CUSTOMER_PRICE, LOCAL_DATETIME,
        CUSTOMER_DATETIME, ID_PLAZO_ENTREGA, TAX, QUANTITY, LINESTATUS,
        ORDER_STATUS, ORDER_PRIORITY, SHIP_DATE, RETURN_FLAG, COMMIT_DATE,
        RECEIPT_DATE, SHIP_INSTRUCT, SHIP_MODE, CLERK, SHIP_PRIORITY
    )
    SELECT
        O.ORDER_DATE, O.C_CUSTKEY, L.P_PARTKEY, L.S_SUPPKEY, O.O_ORDERKEY,
        CASE
            WHEN O.O_ORDERSTATUS = 'O' THEN 'venta'
            ELSE 'devolucion'
        END AS ORDERTYPE,
        S.STORE_ID, E.EVENT_ID,
        L.L_EXTENDEDPRICE * ER_STORE.EXCHANGE_USD AS LOCAL_PRICE,
        L.L_EXTENDEDPRICE * ER_CUSTOMER.EXCHANGE_USD AS CUSTOMER_PRICE,
        CONVERT_TZ(O.O_ORDERDATE, 'UTC', T_STORE.UTC) AS LOCAL_DATETIME,
        CONVERT_TZ(O.O_ORDERDATE, 'UTC', T_CUSTOMER.UTC) AS CUSTOMER_DATETIME,
        L.L_TASK, L.L_QUANTITY, L.L_LINESTATUS, O.O_ORDERSTATUS, O.O_ORDERPRIORITY,
        L.L_SHIPDATE, L.L_RETURNFLAG, L.L_COMMITDATE, L.L_RECEIPTDATE,
        L.L_SHIPINSTRUCT, L.L_SHIPMODE, CAST(REGEXP_SUBSTR(O.O_CLERK, '[0-9]+') AS UNSIGNED),
        O.O_SHIPPRIORITY
    FROM ORDERS O
    JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
    JOIN STORE S ON S.NATION = L.L_SHIPINSTRUCT
    JOIN EVENT E ON O.ORDER_DATE BETWEEN E.START_DATE AND E.END_DATE AND S.NATION = E.NATION
    JOIN EXCHANGE_RATE ER_STORE ON S.NATION = ER_STORE.NATION AND O.ORDER_DATE = ER_STORE.ORDER_DATE
    JOIN EXCHANGE_RATE ER_CUSTOMER ON O.C_CUSTKEY = ER_CUSTOMER.NATION AND O.ORDER_DATE = ER_CUSTOMER.ORDER_DATE
    JOIN TIME_ZONE T_STORE ON S.NATION = T_STORE.NATION
    JOIN TIME_ZONE T_CUSTOMER ON O.C_CUSTKEY = T_CUSTOMER.NATION
    WHERE O.ORDER_DATE >= CURRENT_DATE - INTERVAL '30 DAY'
    AND L.L_SHIPDATE IS NOT NULL;
$$;
