-- Código para actualizar tiempos de entrega
CREATE PROCEDURE update_delivery_times()
RETURNS STRING
LANGUAGE SQL
AS
$$
    UPDATE DAILY_SALES
    SET ID_PLAZO_ENTREGA =
        CASE
            WHEN DATEDIFF(DAY, COMMIT_DATE, RECEIPT_DATE) > 30 THEN 0
            WHEN DATEDIFF(DAY, COMMIT_DATE, RECEIPT_DATE) <= 0 THEN 1
            WHEN DATEDIFF(DAY, COMMIT_DATE, RECEIPT_DATE) BETWEEN 1 AND 10 THEN 2
            WHEN DATEDIFF(DAY, COMMIT_DATE, RECEIPT_DATE) BETWEEN 11 AND 30 THEN 3
        END;
$$;